### ISSUE TITLE
Push Assignments

### ISSUE THREAD

**Issue by dojo-json** [CodingDojo-MEAN-06-18/Harika_P#1]
Please push your latest assignments.

**Comment by dojo-json** [comment]
@pharika31  Any updates on this?

**Comment by pharika31** [comment]
Started working on the backlogs. Will try to upload them by the end of this week.

**Comment by dojo-json** [comment]
Thanks for updating your assignments.

I recommend closing this issue automatically with your next push. Check out the documentation for closing issues with keywords: https://help.github.com/articles/closing-issues-using-keywords/

TLDR: Create a commit message that contains something like `closes #1`. Github will detect the keyword and close the issue.

**Comment by dojo-json** [comment]
Please update your repo with your latest completed assignments.
